// photos.js

// Define the array of photo URLs
const photos = [
    'Alsike_Clover_Flower.JPG',
    'Sunset_Splash.JPG',
    'Wild_Mushroom.JPG',
    'busy_bees.jpg',
    'Firework_Fairie.JPG',
    'Pacific_Grove_Sunset.JPG',
    'Majestic Beauty 2.jpg',
    'Fern_Falls.JPG',
    'The Entry Way to The Unknown.JPG',
    'Tanis_(15).JPG',
    'Sun_streaked_mighty_Oak.JPG',
    'Aunt_Fanny.jpg',
    'feather_fireworks.JPG',
    'Orange_Sunset_Pacific_Grove.jpg',
    'Grace.jpg',
    'Sunset_over_Lake_Coeur_D_Alene.jpg',
    'She_is_a_hard_worker.jpg',
    'Fall_in_Hollister.jpg',
    'Light_blooms.jpg',
    'Beautiful_Clouds.JPG',
    'antiqued_look.JPG',
    'Long_Armed_Oak.jpg',
    'Julyamsh_Pow_Wow.png',
    'Leatherwood_Recreational_Area.jpg',
    'Pink_&_ Denim_Sunset.jpg',
    'Firey_Sunset_Over_PG.JPG',
    'Bee_Bread.jpg',
    'San_Juan_Bautista_Night_Sky.jpg',
    'Georgetown_Evening.jpg',
    'Carpenter_Bee.jpg',
    'Tanis_Wedding.JPG',
    'Tanis_Boquet.JPG',
    'Pink_Blooms_in_Pacific_Grove.jpg',
    'Seals_Under_Santa_Cruz_Pier.JPG',
    'Carmel_By_The_Sea.JPG',
    'Breath_Taking_Sunset.JPG',
    'Pink_Clouds.JPG',
    'Wild_Raspberries.JPG',
    'Not_where_its_Supposed_to_Be.JPG',
    'San_Juan_Bautista_Mission_Rose.JPG',
    'Chillin_Duck.JPG',
    'cake.JPG',
    'View_of_Nectar.jpg',
    'Tinkerbell.jpg',
    'Beautiful_House.JPG.png',
    'Croc.JPG',
    'Palm_Firesky.jpg',
    'Mesmerizing_Sunset.jpg',
    'The_Point_in_Monterey.jpg',
    'Dragonfly3.JPG',
    'Baby_Brids.JPG',
    'Focused.JPG',
    'Sunset_on_the_Prairie.JPG',
    'Negative_Beach_&_Clouds.JPG',
    'Sunset_Kissed_Wheat.JPG',
    'The_Dance.JPG',
    'Dainty_Mushroom.JPG',
    'Fern_Falls_Landscape.JPG',
    'Old_Barn.JPG',
    'Beautiful_Summer_Evening.JPG',
    'Lake_CDA.JPG',
    'negflowers.JPG',
    'Break_In_the_Storm.JPG',
    'Looks_Like_Coral.JPG',
    'The_Pumpkin.JPG',
    'Ocean_Spray.JPG',
    'Tanis_(61).JPG',
    'CDA_Sunset.JPG',
    'Nice_lil_creek_waterfall.JPG',
    'Gorgeous_Sunset.JPG',
    'Peaking_at_Fern_Falls.JPG',
    'Tanis_(75).JPG',
    'Palouse_Falls.JPG',
    'Wild_Raspberries2.JPG',
    'Wild_Flower.JPG',
    'Combine_Harvester.JPG',
    'Tanis_(109).JPG',
    'Tanis_(81).JPG',


    
    // Add more photos as needed
];
